#! /usr/bin/python
# vim: set tabstop=4 expandtab shiftwidth=4 :
# Generated by letscode

"""Docstring for Python module"""

import collections

# Python 2/3 compatibility
try:
    basestring
except NameError:
    basestring = (str, bytes)


def flatten(l):
    for el in l:
        if isinstance(el, collections.Iterable) and \
                not isinstance(el, basestring):
            for sub in flatten(el):
                yield sub
        else:
            yield el

wallet = [
    'spare change',
    'id card',
    'organ donor card',
    'debit card',
    'transportation card',
    'emergency contacts',
]

basic_stuff = [
    wallet,
    'phone',
    'keys (home)',
    'bag',
    'tissues',
    'tickets restau',
    'pen and paper',
]

job = [
    basic_stuff,
    'job access card',
]

tourism_stuff = [
    'travel guide',
    'antitheft travel bag',
]


medical_appointment = [
    'health record booklet',
    'vaccination card',
    'vitale card',
    'form of payment (card, checkbook)'
]

shopping = [
    'bags',
    'loyalty card',
    'vouchers/gift cards',
]

abroad = [
    'currency',
    'traveler\'s checks',
    'AC/DC adaptor',
    'vaccine/medicine',
    'visa/passport',
]

stuff_to_sleep_anywhere = [
    'earplugs',
    'eye mask',
    'travel pillow',
    'blanket',
]

sun_stuff = [
    'sun screen',
    'sunburn relief (Biafine)',
    'sun glasses',
    'lip sun protection'
    'cap',
    'short pants',
]

rain_stuff = [
    'umbrella',
    'shoes for the rain',
    'coat',
    'poncho',
]

cold_stuff = [
    'gloves',
    'scarf/neck tube',
    'wooly hat',
    'ski jackets',
    'ski pants',
    'lip balm (cold)',
]

very_cold_stuff = [
    cold_stuff,
    'warm tights',
    'warm socks',

]

beach_stuff = [
    'swimming suit (beach)',
    'towel (beach)',
    'flip-flop',
    'beach games (molky, racket ball, foot ball, petanque balls)',
    'kite',
    'drone',
    'aquashoes',
    'neoprene suit',
    'bag for wet clothes',
    sun_stuff,
]

locker_stuff = [
    'padlock or coin for locker'
]

snorkeling_stuff = [
    'swimming suit',
    'snorkeling mask',
    'snorkel',
    'fins',
]

hygiene_stuff = [
    'toothbrush',
    'toothpaste',
    'shampoo',
    'soap',
    'hair brush/comb',
    'towel (hygiene)',
    'ear buds',
    'deodorant',
    'basic medicine (bandages, fever reliever, etc)',
    'hand sanitizer/wet wipes',
]

everyday_clothes = [
    'socks',
    'underwears',
    'pants/jeans',
    'tshirts/shirts',
    'sweat shirt',
]

fancy_clothes = [
    'suit',
    'fancy shirt',
    '',
    'fancy shoes',
    'belt',
    'tie',
    'cufflink',
    'shaving stuff (razor, cream, etc)',
    'make up'
]

glasses_and_co = [
    'glasses',
    'eyeglass case',
    'contact lenses',
    'box for contact lenses',
    'liquid for contact lenses'
]

proper_sleeping_stuff = [
    glasses_and_co,
    hygiene_stuff,
    'pyjama',
    'laundry bag',
    'slippers',
]

hostel_stuff = [
    locker_stuff,
    'flip-flop',
    stuff_to_sleep_anywhere,
    proper_sleeping_stuff,
]

bike_stuff = [
    'bike',
    'bike lights',
    'bike repair kit',
]

tropical_stuff = [
    'bug repellent',
    'mosquito net',
    'sting reliever',
]

fire_stuff = [
    'firelighter',
]

camping_stuff = [
    'tente',
    '(inflatable) mat',
    'pump for the mat',
    'sleeping bag',
    'flashlight',
    'toilet paper',
    'bin bags',
    proper_sleeping_stuff,
    fire_stuff,
]

cleaning_stuff = [
    'bin bags',
    'kitchen roll',
    'toilet paper',
    'dish soap',
    'sponge',
    'dish tower',
]

dyi_stuff = [
    'protection mask',
    'protection glasses',
    'protection gloves',
    'hammer',
    'screwdrivers',
]

camera = [
    'camera',
    'non-full SD card',
    'charged battery-pack (camera)',
    'charger (camera)',
    'tripod',
]

gift_stuff = [
    'gift',
    'wrapping paper',
]

birthday_stuff = [
    'candles',
    'firelighter',
    'cake',
    gift_stuff,
    camera,
]

wedding_stuff = [
    'invitation',
    'checkbook',
    fancy_clothes,
    camera,
]

trip_stuff = [
    camera,
    'id/passport',
    'entertainment for the trip (books, kindle, music, game)',
]

car_stuff = [
    'GPS',
    'license',
    'registration certificate',
    'car keys',
    'car lighter charger',
    'music playable in the car (USB sticks, line-in cable, etc)',
    'motion sickness pills',
]

long_trip_stuff = [
    'food/drink for the trip',
    stuff_to_sleep_anywhere,
    trip_stuff,
]

train_trip_stuff = [
    'tickets',
    'discount card',
    trip_stuff,
]

flight_trip_stuff = [
    '/!\ nothing dangerous',
    '/!\ liquids in little bags'
    'tickets and/or boarding pass',
    trip_stuff,
]

picnic_stuff = [
    'bottle opener/corkscrew',
    'disposable cutlery/plates/cups',
    'kitchen roll',
    'bin bags',
    'blanket',
]

things_to_download_and_or_print = [
    'bookings (flights, trains, car, hotels, etc)',
    'addresses (hotels, friends)'
    'messaging app',
    'offline maps',
    'yuge',
]

electronics = [
    'computer',
    'charger (computer)',
    'phone',
    'charger (phone)',
    'watch',
    'charger (watch)',
    'multi-socket adaptor',
]

london = [
    abroad,
    trip_stuff,
    proper_sleeping_stuff,
    'oyster card',
]

basic_observation = [
    'binoculars',
]

show_stuff = [
    'binoculars',
]

gig_stuff = [
    show_stuff,
    'earplugs',
    'water bottle with additional caps'
]

festival = [
    'earplugs',
    'water',
    'biscuits',
    'tickets',
    'deck of cards',
    gig_stuff,
    rain_stuff,
]


sport_locker_room_stuff = [
    locker_stuff,
    'towel (sport)',
    'soap',
]


swimming_pool_stuff = [
    sport_locker_room_stuff,
    'swimming suit (swimming-pool)',
    'swimming hat',
    'nose clip',
    'fins',
    'pull-buoy'
    'bag for wet clothes',
]

sport_stuff = [
    sport_locker_room_stuff,
    'water (bottle or flask)',
    'sport clothes (shorts, tshirt)',
    'clean clothes',
]


extreme_sport_stuff = [
    sport_stuff,
    'eyeglass strap',
]

skiing_stuff = [
    sun_stuff,
    cold_stuff,
    extreme_sport_stuff,
    'ski goggles',
    'ski helmet',
    'snow boot',
    'muscle healing cream',
]


sauna_hammam = [
    'towel (sauna)',
    'bath robe',
    'flip-flop',
    'black soap',
    'scrubbing glove',
]

climbing = [
    extreme_sport_stuff,
    'climbing shoes',
    'harness',
    'rope'
    'climbing stuff',
    'nail clippers',
]

hiking_stuff = [
    'maps',
    'compass',
    'med pack',
    basic_observation,
]

interstellar_hitch_hiking_stuff = [
    'towel',
    'Hitchhiker\'s Guide to the Galaxy'
]

girl_stuff = [
    'stuff for period (tampon, sanitary tower, related medicine)',
]


def main():
    """Main function"""
    print('\n'.join(sorted(set(flatten(london)))))

if __name__ == "__main__":
    main()
