#! /usr/bin/python
# vim: set tabstop=4 expandtab shiftwidth=4 :
# Generated by letscode

"""Docstring for Python module"""

# WORK IN PROGRESS

portefeuille = [
    'monnaie',
    'carte d\identite',
    'carte de donneur d\'organe',
    'carte de credit',
    'carte de transport',
    'contacts d\'urgence',
]

trucs_de_base = [
    portefeuille,
    'telephone',
    'cles (maison)',
    'sac',
    'mouchoirs',
    'tickets restau',
    'paper et crayon',
]

boulot = [
    trucs_de_base,
    'badge du boulot',
]

trucs_de_tourisme = [
    'guide de tourisme',
    'sacoche de voyage antivol',
]

rdv_medical = [
    'carnet de sante',
    'carnet de vaccination',
    'carte vitale',
    'moyen de payment (carte de credit, chequier)'
]

shopping = [
    'sacs',
    'carte de fidelite',
    'coupons/bons cadeaux',
]

etranger = [
    'devises etrangeres',
    'traveler\'s checks',
    'adaptateur electrique',
    'vaccins/medicaments',
    'visa/passeport',
]

trucs_pour_dormir_partout = [
    'boules Quies',
    'masque pour dormir',
    'oreiller de voyage',
    'couverture',
]

trucs_pour_le_soleil = [
    'creme solaire',
    'creme anti-brulure (Biafine)',
    'lunettes de soleil',
    'baume a levres solaire'
    'casquette',
    'short',
]

trucs_pour_la_pluie = [
    'parapluie',
    'chaussures etanges',
    'manteau',
    'poncho',
]

trucs_pour_le_froid = [
    'gantss',
    'echarpe/tour de cou',
    'bonnet',
]

trucs_pour_le_tres_froid = [
    trucs_pour_le_froid,
    'collants chauds',
    'grosses chaussettes',
    'veste de ski'
    'pantalon de ski',
    'baume a levre anti-gercures',
]

trucs_de_plage = [
    'maillot de bain (plage)',
    'serviette (plage)',
    'tongs',
    'jeux de plage (molky, raquettes, ballon de foot, petanque)',
    'cerf-volant',
    'drone',
    'aquashoes',
    'vetements en neoprene',
    'sacs pour vetements mouilles',
    trucs_pour_le_soleil,
]

truc_pour_casier = [
    'cadenas ou piece pour le casier'
]

trucs_pour_le_snorkeling = [
    'maillot de bain',
    'masque de plongees',
    'tuba',
    'palmes',
]

kit_premiers_soins = [
    'bandages',
    'fever reliever',
]

medecine_de_base = [
    kit_premiers_soins,
    'food supplement',
]

trucs_d_hygiene = [
    'brosse a dents',
    'dentifrice',
    'shampoing',
    'savon',
    'peigne/brosse a cheveux',
    'serviette (pour se laver)',
    'coton-tiges',
    'deodorant',
    'get pour se laver les mains/lingettes',
    medecine_de_base,
]

everyday_clothes = [
    'socks',
    'underwears',
    'pants/jeans',
    'tshirts/shirts',
    'sweat shirt',
]

vetements_classes = [
    'suit',
    'fancy shirt',
    'collar stays',
    'fancy shoes',
    'belt',
    'tie',
    'cufflink',
    'shaving stuff (razor, cream, etc)',
    'make up'
]

glasses_and_co = [
    'glasses',
    'eyeglass case',
    'contact lenses',
    'box for contact lenses',
    'liquid for contact lenses'
]

proper_sleeping_stuff = [
    glasses_and_co,
    trucs_d_hygiene,
    'pyjama',
    'laundry bag',
    'slippers',
]

hostel_stuff = [
    truc_pour_casier,
    'flip-flop',
    trucs_pour_dormir_partout,
    proper_sleeping_stuff,
]

bike_stuff = [
    'bike',
    'bike lights',
    'bike repair kit',
]

tropical_stuff = [
    'bug repellent',
    'mosquito net',
    'sting reliever',
]

fire_stuff = [
    'firelighter',
]

camping_stuff = [
    'tente',
    '(inflatable) mat',
    'pump for the mat',
    'sleeping bag',
    'flashlight',
    'toilet paper',
    'bin bags',
    proper_sleeping_stuff,
    fire_stuff,
]

cleaning_stuff = [
    'bin bags',
    'kitchen roll',
    'toilet paper',
    'dish soap',
    'sponge',
    'dish tower',
]

dyi_stuff = [
    'protection mask',
    'protection glasses',
    'protection gloves',
    'hammer',
    'screwdrivers',
]

camera = [
    'camera',
    'non-full SD card',
    'charged battery-pack (camera)',
    'charger (camera)',
    'tripod',
]

gift_stuff = [
    'gift',
    'wrapping paper',
    'nice card',
]

trucs_d_anniversaire = [
    'bougies',
    'briquet',
    'gateau',
    gift_stuff,
    camera,
]

trucs_de_mariage = [
    'invitation',
    'chequier',
    vetements_classes,
    camera,
]

trip_stuff = [
    camera,
    'id/passport',
    'entertainment for the trip (books, kindle, music, game)',
]

car_stuff = [
    'GPS',
    'license',
    'registration certificate',
    'car keys',
    'car lighter charger',
    'music playable in the car (USB sticks, line-in cable, etc)',
    'motion sickness pills',
]

long_trip_stuff = [
    'food/drink for the trip',
    trucs_pour_dormir_partout,
    trip_stuff,
]

train_trip_stuff = [
    'tickets',
    'discount card',
    trip_stuff,
]

flight_trip_stuff = [
    '/!\ nothing dangerous',
    '/!\ liquids in little bags'
    'tickets and/or boarding pass',
    trip_stuff,
]

picnic_stuff = [
    'bottle opener/corkscrew',
    'disposable cutlery/plates/cups',
    'kitchen roll',
    'bin bags',
    'blanket',
]

things_to_download_and_or_print = [
    'bookings (flights, trains, car, hotels, etc)',
    'addresses (hotels, friends)'
    'messaging app',
    'offline maps',
    'yuge',
]

electronics = [
    'computer',
    'charger (computer)',
    'phone',
    'charger (phone)',
    'watch',
    'charger (watch)',
    'multi-socket adaptor',
]

london = [
    etranger,
    trip_stuff,
    proper_sleeping_stuff,
    'oyster card',
]

basic_observation = [
    'binoculars',
]

show_stuff = [
    'binoculars',
]

gig_stuff = [
    show_stuff,
    'earplugs',
    'water bottle with additional caps'
]

festival = [
    'earplugs',
    'water',
    'biscuits',
    'tickets',
    'deck of cards',
    gig_stuff,
    trucs_pour_la_pluie,
]


sport_locker_room_stuff = [
    truc_pour_casier,
    'towel (sport)',
    'soap',
]


swimming_pool_stuff = [
    sport_locker_room_stuff,
    'swimming suit (swimming-pool)',
    'swimming hat',
    'nose clip',
    'fins',
    'pull-buoy'
    'bag for wet clothes',
]

sport_stuff = [
    sport_locker_room_stuff,
    'water (bottle or flask)',
    'sport clothes (shorts, tshirt)',
    'clean clothes',
]


extreme_sport_stuff = [
    sport_stuff,
    'eyeglass strap',
]

skiing_stuff = [
    trucs_pour_le_soleil,
    trucs_pour_le_tres_froid,
    extreme_sport_stuff,
    'ski goggles',
    'ski helmet',
    'snow boot',
    'muscle healing cream',
]


sauna_hammam = [
    'serviette (sauna)',
    'bath robe',
    'flip-flop',
    'black soap',
    'scrubbing glove',
]

climbing = [
    extreme_sport_stuff,
    'climbing shoes',
    'harness',
    'rope'
    'climbing stuff',
    'nail clippers',
]

hiking_stuff = [
    'maps',
    'compass',
    'walking shoes',
    'water',
    'snacks',
    kit_premiers_soins,
    basic_observation,
]

interstellar_hitch_hiking_stuff = [
    'serviette',
    'Hitchhiker\'s Guide to the Galaxy'
]

girl_stuff = [
    'stuff for period (tampon, sanitary tower, related medicine)',
]
