#! /usr/bin/python
# vim: set tabstop=4 expandtab shiftwidth=4 :
# Generated by letscode

"""Docstring for Python module"""

portefeuille = [
    'monnaie',
    'carte d\'identite',
    'carte de donneur d\'organe',
    'carte de credit',
    'carte de transport',
    'contacts d\'urgence',
]

trucs_de_base = [
    portefeuille,
    'telephone',
    'cles (maison)',
    'sac',
    'mouchoirs',
    'tickets restau',
    'papier et crayon',
    'casque audio/ecouteurs',
]

boulot = [
    trucs_de_base,
    'badge du boulot',
]

trucs_de_tourisme = [
    'guide de tourisme',
    'sacoche de voyage antivol',
]

rdv_medical = [
    'carnet de sante',
    'carnet de vaccination',
    'carte vitale',
    'attestation de mutuelle',
    'moyen de payment (carte de credit, chequier)',
]

shopping = [
    'sacs',
    'carte de fidelite',
    'coupons/bons cadeaux',
]

etranger = [
    'devises etrangeres',
    'traveler\'s checks',
    'adaptateur electrique',
    'vaccins/medicaments',
    'visa/passeport',
    'vocabulaire minimal dans la langue etrangere',
    'permis de conduire international (ou traduction)',
]

trucs_pour_dormir_partout = [
    'boules Quies',
    'masque pour dormir',
    'oreiller de voyage',
    'couverture',
    'boite a lunettes',
]

trucs_pour_le_soleil = [
    'creme solaire',
    'creme anti-brulure (Biafine)',
    'lunettes de soleil',
    'baume a levres solaire',
    'casquette',
    'short',
    'eventail',
]

trucs_pour_la_pluie = [
    'parapluie',
    'chaussures etanches',
    'manteau',
    'poncho',
]

trucs_pour_le_froid = [
    'gants',
    'echarpe/tour de cou',
    'bonnet',
    'creme pour les mains',
]

trucs_pour_le_tres_froid = [
    trucs_pour_le_froid,
    'collants chauds',
    'grosses chaussettes',
    'veste de ski',
    'pantalon de ski',
    'baume a levre anti-gercures',
]

jeux_d_exterieur = [
    'molky',
    'raquettes',
    'ballon de foot',
    'petanque',
    'frisbee',
    'cerf-volant',
    'drone',
]

trucs_de_plage = [
    'maillot de bain (plage)',
    'serviette (plage)',
    'tongs',
    'aquashoes',
    'vetements en neoprene',
    'sacs pour vetements mouilles',
    trucs_pour_le_soleil,
    jeux_d_exterieur,
]

truc_pour_casier = [
    'cadenas ou piece pour le casier',
]

trucs_de_snorkeling = [
    'maillot de bain',
    'masque de plongees',
    'tuba',
    'palmes',
    'creme solaire minerale',  # moins toxique pour les creatures dans l'ea moins toxique pour les creatures dans l'eau
]

trucs_de_plongee = [
    'brevet de plongee',
    'certificat medical',
    'materiel de plongee',
    trucs_de_snorkeling,
],

kit_premiers_soins = [
    'bandages',
    'medicaments contre la fievre',
]

medecine_de_base = [
    kit_premiers_soins,
    'ordonnance',
    'complements alimentaires',
    'preservatifs',
]

trucs_de_coiffure = [
    'brosse a cheveux',
    'peigne',
    'elastiques a cheveux',
]

trucs_d_hygiene = [
    'brosse a dents',
    'dentifrice',
    'shampoing',
    'savon',
    'gant de toilette',
    'serviette (pour se laver)',
    'coton-tiges',
    'deodorant',
    'gel pour se laver les mains/lingettes',
    'charlotte a cheveux',
    'pince a epiler',
    medecine_de_base,
    trucs_de_coiffure,
]

vetements_de_tous_les_jours = [
    'chaussettes',
    'sous-vetements',
    'pantalon/jeans',
    'tshirts/chemises',
    'pull',
]

maquillage = [
    'miroir',
    'maquillage',
    'demaquillant',
]

vetements_classes_femme = [
    maquillage,
]

vetements_classes_homme = [
    'costume',
    'chemise classe',
    'baleines de col',
    'ceinture',
    'cravatte',
    'boutons de manchette',
    'materiel de rasage (rasoir, creme, etc)',
]

vetements_classes = [
    'chaussures classes',
    'brosse a habits',
    vetements_classes_femme,
    vetements_classes_homme,
]

trucs_optiques = [
    'lunettes',
    'boite a lunettes',
    'chiffon a lunettes',
    'lentilles de contact',
    'boite a lentilles de contact',
    'liquide pour lentilles de contact',
]

trucs_pour_vraiment_dormir = [
    trucs_optiques,
    trucs_d_hygiene,
    'pyjama',
    'sac a linge sale',
    'chaussons',
]

trucs_d_auberge_de_jeunesse = [
    truc_pour_casier,
    'tongs',
    trucs_pour_dormir_partout,
    trucs_pour_vraiment_dormir,
]

affaires_de_vestiaires = [
    truc_pour_casier,
    'serviette (sport)',
    'savon',
]

trucs_de_sports = [
    affaires_de_vestiaires,
    'eau (bouteille ou gourde)',
    'vetements de sport (short, tshirt)',
    'vetement de rechange',
]

trucs_sports_extremes = [
    trucs_de_sports,
    'cordon pour lunettes',
    'camera d\'action (et accessoires)',
    'montre etanche qui ne craint rien',
]

trucs_de_velo = [
    'velo',
    'casque de velo',
    'antivol de velo',
    'lampes de velo',
    'pompe a velo',
    'chambre a air',
    'kit de reparation de velo',
    'porte-cartes/porte-telephone pour velo',
    'constat en cas d\'accident',
    'gilet fluo',
    trucs_sports_extremes,
]

trucs_pour_zones_tropicales = [
    'anti-moustiques',
    'moustiquaire',
    'trucs anti-piqures',
    'vetements a manches longues',
]

trucs_pour_faire_du_feu = [
    'allume-feu',
]

trucs_de_camping = [
    'tente',
    'matelas pneumatique',
    'pompe a matelas',
    'sac de couchage',
    'lampe de poche',
    'papier toilette',
    'sacs poubelle',
    trucs_pour_vraiment_dormir,
    trucs_pour_faire_du_feu,
]

materiel_de_nettoyage = [
    'sacs poubelle',
    'essuie-tout',
    'papier toilette',
    'liquide vaisselle',
    'eponge',
    'torchon a vaiselle',
]

material_de_bricolage = [
    'masque de protection',
    'lunettes de protection',
    'gants de protection',
    'marteau',
    'tournevis',
]

appareil_photo = [
    'appareil_photo',
    'carte SD non remplie',
    'batterie chargee (appareil_photo)',
    'chargeur batterie (appareil_photo)',
    'trepied',
]

cadeau = [
    'cadeau',
    'papier cadeau',
    'carte pour un petit mot',
]

trucs_d_anniversaire = [
    'bougies',
    'briquet',
    'gateau',
    cadeau,
    appareil_photo,
]

trucs_d_eglise = [
    'monnaie pour la quete',
]

trucs_de_mariage = [
    'invitation',
    'chequier',
    vetements_classes,
    appareil_photo,
    trucs_d_eglise,
]

trucs_d_enterrement = [
    'mouchoirs',
    vetements_classes,
    trucs_d_eglise,
]

trucs_de_voyage = [
    appareil_photo,
    'carte d\'identite/passeport',
    'occupations pour le voyage (livres (avec marque-page), kindle, musique, jeu)',
]

trucs_de_voiture = [
    'GPS',
    'permis de conduire (+ permis international ou traduction)',
    'disque jeune conducteur',
    'disque de stationnement',
    'papiers du vehicule',
    'cles de voiture',
    'lunettes pour conduire',
    'adaptateur allume-cigares',
    'musique jouable dans la voiture (cles USB sticks, cable line-in, etc)',
    'support pour telephone',
    'medicaments contre le mal du transport',
    'constat en cas d\'accident',
]

trucs_de_bateau = [
    'medicaments contre le mal de mer',
]

trucs_de_long_voyage = [
    'nourriture/boisson pour le voyage',
    trucs_pour_dormir_partout,
    trucs_de_voyage,
]

trucs_de_voyage_en_train = [
    'tickets',
    'carte de reduction',
    trucs_de_voyage,
]

trucs_de_voyage_en_avion = [
    '/!\ rien de dangereux',
    '/!\ liquide dans des petits sacs',
    'tickets et/ou boarding pass',
    'chaussettes de contention',
    trucs_de_voyage,
]

trucs_de_piquenique = [
    'couteau',
    'ouvre-bouteille/decapsuleur',
    'couverts/assiettes/gobelets jetables',
    'essuie-tout',
    'sacs poubelle',
    'couverture',
    jeux_d_exterieur,
]

trucs_a_telecharger_ou_a_imprimer = [
    'reservations (vols, trains, voiture, hotels, etc)',
    'addresses (hotels, amis)',
    'app de messagerie',
    'cartes routieres hors-ligne',
    'dictionnaire hors-ligne',
    'app pour faire les comptes',
    'yuge',
    'musique/films/series/livres/audiobooks/podcasts',
]

electronique = [
    'ordinateur',
    'chargeur (ordinateur)',
    'telephone',
    'chargeur (telephone)',
    'montre',
    'chargeur (montre)',
    'multiprise',
]

london = [
    etranger,
    trucs_de_voyage,
    trucs_pour_vraiment_dormir,
    'oyster card',
]

observation = [
    'jumelles',
]

trucs_de_cinema = [
    'tickets',
    'lunettes 3D',
]

trucs_de_spectacle = [
    'jumelles',
    'tickets',
]

trucs_de_theatre = [
    trucs_de_spectacle,
    'monnaie pour les ouvreuses',
]

trucs_de_concerts = [
    trucs_de_spectacle,
    'boules Quies',
    'bouteilles d\'eau avec des bouchons en plus',
]

festival = [
    'eau',
    'biscuits',
    'jeu de cartes',
    'gobelets recyclables',
    'porte gobelet',
    'briquet',  # pour bruler les bouts de bracelets
    trucs_de_concerts,
    trucs_pour_la_pluie,
]


trucs_de_piscine = [
    affaires_de_vestiaires,
    'maillot de bain (piscine)',
    'bonnet de bain',
    'pince nez',
    'palmes',
    'pull-buoy',
    'sacs pour vetements mouilles',
]

trucs_de_ski = [
    trucs_pour_le_soleil,
    trucs_pour_le_tres_froid,
    trucs_sports_extremes,
    'masque de ski',
    'casque de ski',
    'apres-ski',
    'creme apaisante pour les muscles',
]


sauna_hammam = [
    'serviette (sauna)',
    'peignoir',
    'tongs',
    'savon noir',
    'gant de toilettes grattant',
]

escalade = [
    trucs_sports_extremes,
    'chaussons d\'escalade',
    'baudrier',
    'corde',
    'vetements d\'escalade',
    'descendeur',
    'degaines',
    'magnesie ou pof',
    'gants d\'assurage',
    'coupe-ongles',
    'lunettes d\'assurage',
]

escalade_en_salle = [
    escalade,
    'tickets/carte pour la salle d\'escalade',
]

escalade_en_exterieur = [
    escalade,
    'vache/longe',
]

trucs_de_rando = [
    'cartes',
    'boussole',
    'chaussures de rando',
    'batons de marche',
    'eau',
    'snacks',
    kit_premiers_soins,
    observation,
]

interstellar_hitch_hiking_stuff = [
    'serviette',
    'Hitchhiker\'s Guide to the Galaxy',
]

trucs_de_filles = [
    'trucs pour les regles (tampons, serviettes, medicaments qui vont bien)',
]

quitter_le_boulot_plusieurs_jours = [
    'parametrer le repondeur email automatique',
    'nettoyer le bureau',
]

quitter_la_maison_plusieurs_jours = [
    'arroser les plantes',
    'vider les poubelles',
    'vider le frigo',
    'debrancher les appareils electroniques inutiles',
]

quitter_le_pays_plusieurs_jours = [
    'prevenir la banque',
]

partir_en_vacances = [
    'desactiver le reveil',
    'retirer les objets inutiles du portefeuille',
]

retour_de_vacances = [
    'activer le reveil',
    'remettre les objets dans le portefeuille',
]
